apiVersion: v2
name: headscale-webui
description: Helm chart for Headscale webui

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

appVersion: "1.16.0"

keywords:
  - ssh
  - vpn
  - headscale
  - tailscale

maintainers:
  - name: Racoon
    email: racoon@hackademint.org
    url: https://gitub.com/Racoon-r

