apiVersion: v1
kind: ConfigMap
metadata:
  name: config-headscale
  labels:
    {{- include "headscale-webui.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ .Values.configHeadscale | toYaml | trim | quote | indent 4 }}
