{{- if (include "headscale-webui.createPVC" .) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "headscale-webui.fullname" . }}
  labels:
    {{- include "headscale-webui.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
